id: "20260225-164328_task"
title: "хотел понять про алгоритм действительно фаза обуче"
session_id: "f671a458-1e90-478f-93fe-40a0c6f8ed9e"
created_at: "2026-02-25T16:43:28+03:00"
completed_at: null
status: "ACTIVE"
